### ISSUE TITLE
Stitching mosaics produces empty output

### ISSUE THREAD

**Issue by lgeistlinger** [BodenmillerGroup/steinbock#116]
Hi, 

I have two z-stack tiffs [here](https://www.dropbox.com/sh/9qa0306bxkjhc8x/AADEmFRb6tTVioMrYVHJ2rUua?dl=0) that I would like to stitch together. Those are actually two tile pieces of a larger mosaic (~400 tiles in total).

I've named the files according to the specification in the [steinbock documentation](https://bodenmillergroup.github.io/steinbock/latest/cli/utils/) by providing tile X and Y position (in pixels) and tile width and height; and have put the two files in a folder named `masks`.

I am then running steinbock as indicated via

```
steinbock utils mosaics stitch masks -o masks_full
```

However, although the output directory `masks_full` is created and the program finishes without an error, the output directory `masks_full` is empty.

Am I missing something?

Thanks!

**Comment by jwindhager** [comment]
Hi @lgeistlinger, thanks for filing this issue!

This likely happens because your TIFFs end with `.tif` and not `.tiff`.

Sorry for this - I'll add detection for `*.tif` files to the next release of steinbock.

Looking at your image files (thanks for sharing!), I also realize that they have an unsupported image shape:
```
>>> from tifffile import imread
>>> imread("dapi_tx3245_ty3766_tw200_th200.tif", squeeze=False).shape
(7, 2048, 2048, 1)
```

You may be interested in #108 in this case.

Hope this helps, and sorry again for the inconvenience!

**Comment by lgeistlinger** [comment]
Excellent, thanks @jwindhager! Renaming to .tiff and stripping off one dimension did the job for me and produced a composite tiff. I am now looking into scaling this up to the 406 tiles instead of just two, and might report back if I encounter any issues, but that does the trick for me for the moment. Thanks!

**Comment by jwindhager** [comment]
Reopening to remind me of the `.tif` file handling issue :innocent:

**Comment by jwindhager** [comment]
Closing as this is tracked in #142
