### ISSUE TITLE
panel value for mesmer object segmentation

### ISSUE THREAD

**Issue by mohamadmilad** [BodenmillerGroup/steinbock#40]
I did not find a document on how to define deepcell values in the panel.csv!

**Comment by jwindhager** [comment]
https://bodenmillergroup.github.io/steinbock/specs/file-types/

https://bodenmillergroup.github.io/steinbock/cli/segmentation/#deepcell

**Comment by mohamadmilad** [comment]
I saw the docs, but there is no specification; like 1 for nuclei and 2 for cytoplasm? or 1 for both?

**Comment by jwindhager** [comment]
From https://bodenmillergroup.github.io/steinbock/specs/file-types/:

Column | Description | Type | Required?
-- | -- | -- | --
deepcell | Group label for DeepCell segmentation <br> (if column is absent, all channels are used separately) | Numeric or empty | no

From https://bodenmillergroup.github.io/steinbock/cli/segmentation/#deepcell:

> Depending on the application, DeepCell requires images of specific dimensions. For example, in the case of cell segmentation using Mesmer, DeepCell expects two-channel images as input, where the first channel must be a nuclear channel (e.g. DAPI) and the second channel must be a membrane or cytoplasmic channel (e.g. E-Cadherin).

> If a deepcell column is present in the steinbock panel file, channels are sorted and grouped according to values in that column to generate the required input for DeepCell [...]

So yes, you can use 1 for nuclei and 2 for cytoplasm

**Comment by jwindhager** [comment]
First, thank you for raising this issue here on GitHub! I hope you find my previous reply helpful.

> I did not find a document on how to define deepcell values in the panel.csv!

In general, if you think the documentation is not clear enough, you're welcome to kindly ask for clarification or to submit a pull request. This is an open source project made available to the community free of charge in the spirit of open research, and keeping to a respectful and mindful style of interaction goes a long way with the community (and the authors :innocent:)
