### ISSUE TITLE
Apply % threshold instead of hot pixel filter in preprocessing

### ISSUE THREAD

**Issue by a-rayford** [BodenmillerGroup/steinbock#67]
Hi, I have had issues with the hot-pixel filtering method not removing outlier pixels that are immediately adjacent to each other (since the function replaces the hot pixel intensity with the **maximum** value in the 8-neighborhood of the pixel). 

One alternative would be to replace with the minimum or mean value of the 8-neighborhood, or zero, however it may be advantageous (to other users as well) to have the option of a % upper threshold, where the top X % of pixel intensities are changed to zero. I have tried to implement this in CellProfiler using RobustThreshold in the Threshold module but it does not seem to handle multipage tiffs like SmoothMultichannel does. Any thoughts on this? Sorry if this is not the right place to post.

**Comment by jwindhager** [comment]
Hi @a-rayford, I've given this another thought: since we cannot possibly incorporate all possible options for preprocessing IMC data, I won't add this functionality at this point, but stick to the "standard" way of hot pixel filtering as published by Zanotelli et al. The steinbock framework is however flexible enough to allow for custom operations (e.g. the code above) in between, e.g., `steinbock preprocess imc images` and downstream commands. I will therefore close this issue for now and hope for your understanding; maybe we can revisit this later, once the community has settled on a strategy.

On a side: I'm aware that the steinbock Python API is still largely undocumented. I hope I'll get to this soon, especially for the functions from the `steinbock.io` module (e.g. the ones used above).
